/**
 * Tag Suggestions for Gem Creation
 *
 * Provides category-specific tag suggestions to help users
 * describe and categorize their gems effectively.
 */

export const GEM_TAG_SUGGESTIONS: Record<string, string[]> = {
  "food-drink": [
    "local cuisine",
    "street food",
    "fine dining",
    "cafe",
    "dessert",
    "breakfast",
    "seafood",
    "vegetarian",
    "traditional",
    "fusion",
    "rooftop dining",
    "family-friendly",
    "romantic",
    "budget-friendly",
    "authentic",
  ],
  "historical-site": [
    "colonial era",
    "spanish heritage",
    "world war 2",
    "museum",
    "ancient",
    "preserved",
    "educational",
    "guided tours",
    "photography",
    "architecture",
    "landmark",
    "historical marker",
    "restoration",
    "UNESCO",
    "national heritage",
  ],
  "art-music": [
    "contemporary art",
    "traditional art",
    "gallery",
    "street art",
    "murals",
    "live music",
    "cultural center",
    "exhibitions",
    "local artists",
    "installations",
    "workshops",
    "performances",
    "cultural events",
    "photography",
    "crafts",
  ],
  nature: [
    "scenic views",
    "hiking",
    "wildlife",
    "gardens",
    "waterfall",
    "beach",
    "mountain",
    "eco-friendly",
    "bird watching",
    "trails",
    "camping",
    "picnic spot",
    "sunset views",
    "family-friendly",
    "protected area",
  ],
  culture: [
    "traditional",
    "festivals",
    "rituals",
    "local customs",
    "heritage",
    "community",
    "cultural exchange",
    "indigenous",
    "folklore",
    "ceremonies",
    "traditional crafts",
    "cultural center",
    "historical",
    "educational",
    "authentic experience",
  ],
  shopping: [
    "local products",
    "handicrafts",
    "souvenirs",
    "market",
    "mall",
    "boutique",
    "antiques",
    "bargain shopping",
    "luxury brands",
    "night market",
    "food market",
    "local artisans",
    "traditional goods",
    "fashion",
    "pasalubong",
  ],
  "religious-site": [
    "church",
    "temple",
    "mosque",
    "shrine",
    "pilgrimage",
    "sacred",
    "historic",
    "architecture",
    "worship",
    "meditation",
    "peaceful",
    "spiritual",
    "religious festivals",
    "heritage site",
    "prayer",
  ],
  viewpoint: [
    "scenic",
    "panoramic",
    "sunrise",
    "sunset",
    "photography",
    "instagram-worthy",
    "city views",
    "ocean views",
    "mountain views",
    "romantic",
    "observation deck",
    "hiking",
    "accessible",
    "360 degrees",
    "landmarks visible",
  ],
  monument: [
    "historical",
    "memorial",
    "statue",
    "landmark",
    "commemorative",
    "public art",
    "iconic",
    "photography",
    "historical significance",
    "national hero",
    "architecture",
    "symbolic",
    "heritage",
    "tourist attraction",
    "war memorial",
  ],
  park: [
    "playground",
    "jogging",
    "picnic",
    "family-friendly",
    "dog-friendly",
    "sports facilities",
    "walking paths",
    "gardens",
    "relaxation",
    "outdoor activities",
    "events venue",
    "free admission",
    "benches",
    "shaded areas",
    "accessible",
  ],
};

/**
 * Get tag suggestions for a specific category
 *
 * @param category - The gem category
 * @returns Array of suggested tags, or empty array if category not found
 *
 * @example
 * ```ts
 * const suggestions = getTagSuggestionsByCategory("food-drink");
 * // Returns: ["local cuisine", "street food", ...]
 * ```
 */
export function getTagSuggestionsByCategory(category: string): string[] {
  return GEM_TAG_SUGGESTIONS[category] || [];
}
